---
abstract: 'A message queue implemented with MongoDB'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Test::Deep: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoDBx-Queue
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MongoDBx::Queue:
    file: lib/MongoDBx/Queue.pm
    version: 1.001
requires:
  MongoDB: 0.702
  Moose: 2
  MooseX::AttributeShortcuts: 0
  MooseX::Role::Logger: 0
  MooseX::Role::MongoDB: 0.003
  MooseX::Types::Moose: 0
  Tie::IxHash: 0
  boolean: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/MongoDBx-Queue/issues
  homepage: https://github.com/dagolden/MongoDBx-Queue
  repository: https://github.com/dagolden/MongoDBx-Queue.git
version: 1.001
x_authority: cpan:DAGOLDEN
